### ISSUE TITLE
Is returning 500 error when accessing OSS Index

### ISSUE THREAD

**Issue by JasonQuinn** [sonatype-nexus-community/nancy#263] opened 2022-05-24 13:37 UTC
Running nancy has started returning a 500 error "Error: An error occurred: [500 Internal Server Error] error accessing OSS Index" when running
https://ossindex.sonatype.org/updates-notice says there were index updates yesterday and today is the 1st day I've seen it so it might be related

* **What are you trying to do?**
Run nancy against my go dependencies with  
`go list -m all | docker run --env GITHUB_TOKEN=$GITHUB_TOKEN  --pull always --rm -i sonatypecommunity/nancy:latest sleuth `

cc @bhamail / @DarthHater

**Comment by sethlivingston** [comment] 2022-05-24 14:51
Looks like this could be related to some changes made yesterday, May 23:

> Some ecosystems will no longer be supported.As part of this change we will be dropping support for Drupal, Debian, Chocolatey, Alpine, Bower and Go Dep. Note: Go Mod will continue to be supported and we encourage all OSS Index users to upgrade to newer Go Mod modules.

Source: https://ossindex.sonatype.org/updates-notice

**Comment by ken-duck** [comment] 2022-05-25 02:40
A fix has been deployed. You should see Nancy working correctly now.

**Comment by harshavardhana** [comment] 2022-05-26 01:36
Looks like now it's broken in different ways

```
Error: Post "https://ossindex.sonatype.org/api/v3/component-report": x509: certificate has expired or is not yet valid: current time 2022-05-26T01:34:29Z is after 2022-05-25T23:59:59Z
```

**Comment by ken-duck** [comment] 2022-05-26 04:46
Sorry for the problem. It should be resolved now. 

Thanks for the heads up!

**Comment by gedge** [comment] 2022-10-18 07:15
this has happened again - I'm getting 500s
```
Error: An error occurred: [500 Internal Server Error] error accessing OSS Index
```

**Comment by redhug1** [comment] 2022-10-18 07:20
I use 1.0.41 version
I'm getting 500s
Error: An error occurred: [500 Internal Server Error] error accessing OSS Index

logfile shows:
{"level":"error","msg":"Error accessing OSS Index","resp_status_code":"500 Internal Server Error","time":"2022-10-18T08:04:08+01:00"}
{"error":"An error occurred: [500 Internal Server Error] error accessing OSS Index","level":"error","msg":"unexpected error in root cmd","time":"2022-10-18T08:04:08+01:00"}

I run with:
go list -m all | nancy sleuth

**Comment by sandypadmanabhan** [comment] 2022-10-18 08:58
I am getting a 500- Internal Server Error

**Comment by TheoBrigitte** [comment] 2022-10-18 12:37
Same error here

```
$ CGO_ENABLED=0 go list -json -m all | nancy sleuth --skip-update-check
Error: An error occurred: [500 Internal Server Error] error accessing OSS Index

For more information, check the log file at /home/theo/.ossindex/nancy.combined.log
nancy version: 0.0.0-dev
...
$ cat /home/theo/.ossindex/nancy.combined.log
{"level":"error","msg":"Error accessing OSS Index","resp_status_code":"500 Internal Server Error","time":"2022-10-18T14:36:07+02:00"}
{"error":"An error occurred: [500 Internal Server Error] error accessing OSS Index","level":"error","msg":"unexpected error in root cmd","time":"2022-10-18T14:36:07+02:00"}
```

**Comment by AmanChh** [comment] 2022-10-18 12:44
Same error here 

Error: An error occurred: [500 Internal Server Error] error accessing OSS Index

**Comment by adamdecaf** [comment] 2022-10-18 15:22
> Any workaround on this until it gets fixed?

Not really. We disabled nancy in our CI pipeline until this is fixed.

**Comment by gedge** [comment] 2022-10-18 16:38
@ken-duck - have you seen this? 🙏

**Comment by JohnStarich** [comment] 2022-10-18 17:38
I can reliably reproduce with this API request:
```
curl -X 'POST' \
  'https://ossindex.sonatype.org/api/v3/component-report' \
  -H 'accept: application/vnd.ossindex.component-report.v1+json' \
  -H 'Content-Type: application/vnd.ossindex.component-report-request.v1+json' \
  -d '{
  "coordinates": [
    "pkg:golang/github.com/IBM-Cloud/go-etcd-rules@v1.5.14"
  ]
}'
```
The version doesn't appear to matter. Any other public golang dependency I try appears to work.

**Comment by harshavardhana** [comment] 2022-10-18 17:44
We moved away from this index to vulncheck by Go community, works like a charm.

**Comment by bhamail** [comment] 2022-10-18 21:01
We're looking into the recent 500 errors from OSSIndex. So far, they errors appear to be project specific (e.g. not universal). Still digging.

**Comment by bhamail** [comment] 2022-10-18 21:34
We found and fixed the problem. It was an edge case bug in a recent update to OSSIndex, and only certain components would have been affected. 

Sorry for the disturbance, and special thanks to @JohnStarich for the helpful report - made it much easier to find the root cause.

**Closed** 2022-10-18 21:35 UTC
