### ISSUE TITLE
go get failing

### ISSUE THREAD

**Issue by marct83** [sonatype-nexus-community/nancy#18] opened 2019-07-30 15:33 UTC
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

go get -u github.com/sonatype-nexus-community/nancy

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**
```go get -u github.com/sonatype-nexus-community/nancy
go: finding github.com/dgryski/go-farm latest
go: finding github.com/coreos/pkg latest
go: finding github.com/coreos/go-systemd latest
go: finding github.com/google/pprof latest
go: finding github.com/jstemmer/go-junit-report latest
go: finding github.com/tmc/grpc-websocket-proxy latest
go: finding golang.org/x/lint latest
go: finding google.golang.org/genproto latest
go: finding github.com/prometheus/client_model latest
go: finding golang.org/x/net latest
go: finding github.com/modern-go/concurrent latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/oauth2 latest
go: finding golang.org/x/sys latest
go: finding github.com/logrusorgru/aurora latest
go: finding golang.org/x/mobile latest
go: finding golang.org/x/time latest
go: finding golang.org/x/exp latest
go: finding github.com/shopspring/decimal latest
go: finding golang.org/x/tools latest
go: finding github.com/armon/consul-api latest
go: finding golang.org/x/crypto latest
go: finding github.com/golang/glog latest
go: finding github.com/mwitkow/go-conntrack latest
go: finding github.com/kr/logfmt latest
go: finding github.com/xiang90/probing latest
go: finding github.com/BurntSushi/xgb latest
go: finding github.com/AndreasBriese/bbloom latest
go: finding gopkg.in/check.v1 latest
go: finding github.com/golang/groupcache latest
go: finding golang.org/x/image latest
go: finding github.com/alecthomas/units latest
go: finding github.com/alecthomas/template latest
go: finding github.com/dgryski/go-sip13 latest
# github.com/sonatype-nexus-community/nancy/audit
audit/auditlog.go:32:15: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
# github.com/sonatype-nexus-community/nancy/ossindex
ossindex/ossindex.go:62:6: opts.Dir undefined (type func(string) badger.Options has no field or method Dir)
ossindex/ossindex.go:63:6: opts.ValueDir undefined (type func(string) badger.Options has no field or method ValueDir)
ossindex/ossindex.go:64:23: cannot use opts (type func(string) badger.Options) as type badger.Options in argument to badger.Open
ossindex/ossindex.go:161:16: txn.SetWithTTL undefined (type *badger.Txn has no field or method SetWithTTL)```

**Comment by logansam** [comment] 2019-07-30 15:49
Same problem here!

**Comment by marct83** [comment] 2019-07-30 15:52
go version go1.12.6 linux/amd64

**Comment by DarthHater** [comment] 2019-07-30 16:37
Interesting! I imagine this is because of the version of Badger it fetches. I'll take a look today!

**Comment by DarthHater** [comment] 2019-07-30 17:28
Fails locally for me too, I'll see if I can resolve it today! Thanks for pointing this out.

**Comment by DarthHater** [comment] 2019-07-30 17:36
Ok, I know what is causing this. The `go get -u` is updating dependencies as it you know, downloads them, so we are ending up with a few dependencies that are too new! If you run `go get` without the u, it should work fine. I'll update the README.md to reflect that, too! Thanks for pointing out the mistake! Close this issue if it works fine for you!

**Comment by marct83** [comment] 2019-07-30 17:52
```go get github.com/sonatype-nexus-community/nancy
# github.com/sonatype-nexus-community/nancy/audit
audit/auditlog.go:32:15: not enough arguments in call to aurora.Gray
	have (string)
	want (uint8, interface {})
# github.com/sonatype-nexus-community/nancy/ossindex
ossindex/ossindex.go:62:6: opts.Dir undefined (type func(string) badger.Options has no field or method Dir)
ossindex/ossindex.go:63:6: opts.ValueDir undefined (type func(string) badger.Options has no field or method ValueDir)
ossindex/ossindex.go:64:23: cannot use opts (type func(string) badger.Options) as type badger.Options in argument to badger.Open
ossindex/ossindex.go:161:16: txn.SetWithTTL undefined (type *badger.Txn has no field or method SetWithTTL)
```

**Comment by DarthHater** [comment] 2019-07-30 17:55
Interesting. When I do it locally I get: ```(base) 504 :~ $ go get github.com/sonatype-nexus-community/nancy
go: finding github.com/sonatype-nexus-community/nancy v0.0.20
go: downloading github.com/sonatype-nexus-community/nancy v0.0.20
go: extracting github.com/sonatype-nexus-community/nancy v0.0.20```

**Comment by marct83** [comment] 2019-07-30 18:11
I wonder if I need to remove the go.sum and then try it again. I will
report back

**Comment by DarthHater** [comment] 2019-07-30 18:13
@marct83 are you trying to just get nancy to use it or to develop? I might rework the README a bit to better reflect some options for either. Interested in y'alls use case!

**Comment by marct83** [comment] 2019-07-30 18:57
My Bad. The last comment I made makes no sense. I'm just trying to get
nancy. I am planning to implement it into our build process but I need go
get to work with it.

**Comment by daxmc99** [comment] 2019-08-15 01:36
I was able to workaround this by failing over to go.mod ` GO111MODULE=on go get github.com/sonatype-nexus-community/nancy`

**Comment by OSSIndex-Admin** [comment] 2019-09-20 03:18
I am having the same problem on my Ubuntu Xenial (16.04) box. Perhaps I can help debug a bit.

**Comment by OSSIndex-Admin** [comment] 2019-09-20 03:21
FYI:

'''kduck@Gir:~/go/src/github.com/sonatype-nexus-community$ go version
go version go1.13 linux/amd64
'''

**Comment by zendern** [comment] 2019-10-05 00:14
@DarthHater I believe this issue can be closed now that #41 was merged.

**Comment by jroberts07** [comment] 2019-10-29 11:31
I am still facing this:

```
➜  go version
go version go1.13 darwin/amd64
➜  go get -u github.com/sonatype-nexus-community/nancy
# github.com/sonatype-nexus-community/nancy/ossindex
../../../../go/src/github.com/sonatype-nexus-community/nancy/ossindex/ossindex.go:62:6: opts.Dir undefined (type func(string) badger.Options has no field or method Dir)
../../../../go/src/github.com/sonatype-nexus-community/nancy/ossindex/ossindex.go:63:6: opts.ValueDir undefined (type func(string) badger.Options has no field or method ValueDir)
../../../../go/src/github.com/sonatype-nexus-community/nancy/ossindex/ossindex.go:64:23: cannot use opts (type func(string) badger.Options) as type badger.Options in argument to badger.Open
../../../../go/src/github.com/sonatype-nexus-community/nancy/ossindex/ossindex.go:161:16: txn.SetWithTTL undefined (type *badger.Txn has no field or method SetWithTTL)
➜  
```

**Comment by jroberts07** [comment] 2019-10-30 10:09
Caused by this breaking changed in the latest release of Badger https://github.com/dgraph-io/badger/pull/874/files

**Comment by DarthHater** [comment] 2019-10-30 20:13
Hmmmm, it was my understanding that `go get <PKG>` did not update the dependencies, does it do that? @zendern do you know?

**Comment by marct83** [comment] 2019-10-30 21:00
I'm getting this:

```go: finding github.com/dustin/go-humanize v1.0.0
# github.com/golang/dep/gps
../../../go/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:149:4: undefined: semver.Constraint
# github.com/sonatype-nexus-community/nancy/ossindex
../../../go/pkg/mod/github.com/sonatype-nexus-community/nancy@v0.0.33/ossindex/ossindex.go:62:6: opts.Dir undefined (type func(string) badger.Options has no field or method Dir)
../../../go/pkg/mod/github.com/sonatype-nexus-community/nancy@v0.0.33/ossindex/ossindex.go:63:6: opts.ValueDir undefined (type func(string) badger.Options has no field or method ValueDir)
../../../go/pkg/mod/github.com/sonatype-nexus-community/nancy@v0.0.33/ossindex/ossindex.go:64:23: cannot use opts (type func(string) badger.Options) as type badger.Options in argument to badger.Open
../../../go/pkg/mod/github.com/sonatype-nexus-community/nancy@v0.0.33/ossindex/ossindex.go:161:16: txn.SetWithTTL undefined (type *badger.Txn has no field or method SetWithTTL)
```

**Comment by zendern** [comment] 2019-10-30 21:28
> Hmmmm, it was my understanding that `go get <PKG>` did not update the dependencies, does it do that? @zendern do you know?

So it doesn't update the dependencies but if you haven't had them before in your GOPATH its going to just grab the latest. I'm going to guess that is what happened. 

I tested the following. 
```
#wipes out any existing instances of badger depenencies
rm -rf $GOPATH/src/github.com/dgraph-io
#sets GO111MODULE to the default value
export GO111MODULE=auto
# see go get fail
go get -v github.com/sonatype-nexus-community/nancy
```

This blows up with the above error being reported. 

```
#switch to instead having GO111MODULE to on
export GO111MODULE=on
# this should now succeed
go get -v github.com/sonatype-nexus-community/nancy
```

Now this will respect our go.mod file and make it actually work since its using the correct version of badger. I validated this while using golang 1.13.1 FWIW.

This is probably an instance of us needing to update the README to call out if you want `go get` to work to with nancy you are going to have to use GO111MODULE=on.

**Closed** 2021-03-16 16:38 UTC
